[package]
name = "cargo-deadlinks"
description = "Cargo subcommand for checking your documentation for broken links"
version = "0.4.0"
authors = ["Maximilian Goisser <goisser94@gmail.com>"]

repository = "https://github.com/deadlinks/cargo-deadlinks"
homepage = "https://github.com/deadlinks/cargo-deadlinks"
readme = "README.md"

license = "MIT OR Apache-2.0"

[dependencies]
html5ever = "0.22"
url = "1.6"
cargo-edit = "0.2"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
env_logger = "0.3"
reqwest = "0.8"
walkdir = "2.1"
rayon = "1.0"
num_cpus = "1.8"

clippy = { version = "0.0.186", optional = true }

[features]
default = []
unstable = [] # For travis-cargo.

travis = []
lint = ["clippy"]
