[package]
name            = "cargo-deadlinks"
description     = "Cargo subcommand for checking your documentation for broken links"
version         = "0.3.0"
authors         = ["Maximilian Goisser <goisser94@gmail.com>"]

repository      = "https://github.com/deadlinks/cargo-deadlinks"
homepage        = "https://github.com/deadlinks/cargo-deadlinks"
readme          = "README.md"

license         = "MIT OR Apache-2.0"

[dependencies]
html5ever = "0.5.3"
tendril = "0.2.2"
string_cache = "0.2.11"

url = "0.5.5"

cargo-edit = "0.1.2"

docopt = "0.6.78"
log = "0.3.5"
env_logger = "0.3.2"
rustc-serialize = "0.3.18"

clippy = { version = "0.0.55", optional = true }

[features]
default = []
unstable = [] # for travis-cargo

travis = []
lint = ["clippy"]
